#include "sam-parse.h"

/* (c) 2019 Astrea Forensics
   Ed Green
   Parser for sam lines */

#define VERSION (5)

void help( void ) {
  printf( "score-filter-sam -m <float> -b <float> -t\n" );
  printf( "Version %d\n", VERSION );
  printf( "(c) 2019 Astrea Forensics; Ed Green\n" );
  printf( "Filters sam lines based on the value in their\n" );
  printf( "AS (alignment score) tags. These tags are\n" );
  printf( "generated by bwa mem.\n" );
  printf( "Takes input from STDIN.\n" );
  printf( "Writes output if and only if:\n" );
  printf( "1. line is a header line (begins with @)\n" );
  printf( "2. The value in the AS field is defined and is\n" );
  printf( "   >= m x insert size + b\n" );
  printf( "3. There is no AS tag\n" );
  printf( "If -t option is specific, just writes a table of:\n" );
  printf( "ID LEN SCORE\n" );
  exit( 0 );
}

int main( int argc, char* argv[] ) {
  extern char* optarg;
  extern int optind;
  float m, b;
  int ich;
  int got_m = 0;
  int got_b = 0;
  int make_table = 0;
  char line[ MAX_LINE_LEN + 1];
  Saml* sp;
  
  while( (ich=getopt( argc, argv, "m:b:t" )) != -1 ) {
    switch(ich) {
    case 'm' :
      m = atof( optarg );
      got_m = 1;
      break;
    case 'b' :
      b = atof( optarg );
      got_b = 1;
      break;
    case 'h' :
      help();
    case 't' :
      make_table = 1;
      break;
    default :
      help();
    }
  }

  if ( !(got_m && got_b) &&
       !make_table ) {
    help();
  }

  sp = (Saml*)malloc(sizeof(Saml));

  while( fgets( line, MAX_LINE_LEN, stdin ) != NULL ) {
    sp->AS = 0;
    sp->isize = 0;
    sp->seq_len = 0;
    if ( line2saml( line, sp ) == 0 ) {
      /* Got a sam line... test it */
      if ( make_table ) {
	printf( "%s %d %d\n", sp->qname, sp->seq_len, sp->AS );
      }
      else {
	if ( good_score( sp, m, b ) ) {
	  printf( "%s", line ); 
	}
      }
    }
    else {
      printf( "%s", line );
    }
  }
  exit( 0 );
}
